#!/bin/bash

# Author: Ahmed Elmelegy
# Date Created: 23/6/2023
# Last Modified: 23/6/2023

# Description
# Creates a backup in ~/bash_course of all files in the home directory

# Usage: 
# backup.sh

echo "test script"
exit 0
